<?php

namespace AppBundle\Repository;

/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRappel()
    {
        $query="
        SELECT DISTINCT v
        FROM AppBundle:Client v
        JOIN AppBundle:Depot d
        WHERE v=d.client and d.statut='En traitement' or v=d.client and d.statut='Partiellement solde'  ";

        return $this->getEntityManager()->createQuery($query)->getResult();
    }
}
