<?php

namespace AppBundle\Repository;

/**
 * KiloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KiloRepository extends \Doctrine\ORM\EntityRepository
{
}
