<?php

namespace AppBundle\Repository;

/**
 * LingeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LingeRepository extends \Doctrine\ORM\EntityRepository
{
}
