<?php

namespace AppBundle\Repository;

/**
 * PoidsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoidsRepository extends \Doctrine\ORM\EntityRepository
{
}
