<?php

namespace AppBundle\Repository;

/**
 * SoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoinRepository extends \Doctrine\ORM\EntityRepository
{
}
