<?php

namespace AppBundle\Repository;

/**
 * Statistique2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Statistique2Repository extends \Doctrine\ORM\EntityRepository
{

    public function getStatique($debut,$fin)
    {
        $query="
        SELECT s
        FROM AppBundle:Statistique2 s
        WHERE s.date BETWEEN '$debut' and '$fin'";

        return $this->getEntityManager()->createQuery($query)->getResult();
    }

}
