<?php

namespace AppBundle\Repository;

/**
 * TypeTissuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTissuRepository extends \Doctrine\ORM\EntityRepository
{
}
